# spring.profile 옵션
# 애플리케이션 실행시 파라미터로 넘어온게 없으면 active 값을 바라보게 됨
spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
logging:
  config: classpath:logback-spring.xml

# --- 을 기준으로 상단은 공통 영역, 하단이 각 Profile의 설정 영역
# 공통 영역의 값은 각 profile 환경에 동일한 설정이 있으면 무시, 없으면 공통 영역의 설정값이 적용
# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할 때 실행시킬 스크립트
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # 테이블을 DROP -> CREATE 순서로 진행
  h2:
    console:
      enabled: true
